name: Build/Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm i

      - name: Build Electron app
        id: build
        run: npm run make

      #- name: Archive binary
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: ${{ matrix.os }}-binary
      #    path: out/make/zip/darwin