name: Publish Electron Forge Build to GitHub Releases

on:
  push:
    branches:
      - master  # Change this to your default branch

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Electron Forge for Windows
        run: npm run desktop-build

      - name: Build Electron Forge for Windows
        run: npm run make

      - name: Archive Windows Build
        run: |
          7z a -tzip algone-studio-win-x64.zip ./out/algone-studio-*/algone-studio.exe
        shell: bash

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: algone-studio-win
          path: algone-studio-win-x64.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Electron Forge for Windows
        run: npm run desktop-build

      - name: Build Electron Forge for macOS
        run: npm run make

      - name: Archive macOS Build
        run: |
          zip -r algone-studio-darwin-x64.zip ./out/algone-studio-*/algone-studio.app
        shell: bash

      - name: Upload MacOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: algone-studio-darwin
          path: algone-studio-darwin-x64.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Electron Forge for Windows
        run: npm run desktop-build

      - name: Build Electron Forge for Linux
        run: npm run make

      - name: Archive Linux Build
        run: |
          zip -j algone-studio-linux-x64.zip ./out/algone-studio-*/algone-studio
        shell: bash

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: algone-studio-linux
          path: algone-studio-linux-x64.zip

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - uses: actions/download-artifact@v3
        id: download-win
        with:
          name: algone-studio-win

      - uses: actions/download-artifact@v3
        id: download-darwin
        with:
          name: algone-studio-darwin

      - uses: actions/download-artifact@v3
        id: download-linux
        with:
          name: algone-studio-linux

      - name: Check semver incremented value
        id: check_incremented_value
        run: |
          string="${{ github.event.head_commit.message }}"
          if [[ $string == *"#minor"* ]]; then
            echo "incremented_value=minor" >> $GITHUB_OUTPUT
          elif [[ $string == *"#major"* ]]; then
            echo "incremented_value=major" >> $GITHUB_OUTPUT
          else
            echo "incremented_value=patch" >> $GITHUB_OUTPUT
          fi

      - name: Create tag
        id: tag
        uses: SOLIDSoftworks/semver-tags@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: 'v'
          default-version: '0.0.1'
          incremented-value: ${{ steps.check_incremented_value.outputs.incremented_value }}

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Windows Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.download-win.outputs.download-path }}/algone-studio-win-x64.zip
          asset_name: algone-studio-win-x64-${{ steps.tag.outputs.semantic-version }}.zip
          asset_content_type: application/zip

      - name: Upload macOS Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.download-darwin.outputs.download-path }}/algone-studio-darwin-x64.zip
          asset_name: algone-studio-darwin-x64-${{ steps.tag.outputs.semantic-version }}.zip
          asset_content_type: application/zip

      - name: Upload Linux Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.download-linux.outputs.download-path }}/algone-studio-linux-x64.zip
          asset_name: algone-studio-linux-x64-${{ steps.tag.outputs.semantic-version }}.zip
          asset_content_type: application/zip
